name: bump and publish

on:
  workflow_call:

jobs:
  bump:
    runs-on: ubuntu-latest
    outputs:
      new_sha: ${{ steps.sha.outputs.SHA }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install bump2version
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install bump2version

      - name: Configure git
        shell: bash
        run: |
          git config user.name github-actions
          git config user.email "38065702145+github-actions[bot]@users.noreply.github.com"

      - name: Bump version
        shell: bash
        run: |
          bump2version patch --tag --verbose

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true

      - name: get sha
        id: sha
        run: |
          sha_new=$(git rev-parse HEAD)
          echo $sha_new
          echo "SHA=$sha_new" >> $GITHUB_OUTPUT


  publish:
    needs: bump
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ needs.bump.outputs.new_sha }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install --no-root

      - name: Show python dependencies
        run: |
          poetry show

      - name: Build package
        run: |
          poetry build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@v1.13.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}
