name: Pull request master

on:
  push:
    branches: [master]

jobs:
  tests:
    uses: ./.github/workflows/test.yml

  push_and_deploy_qa:
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Build Image
        id: build
        uses: cern-sis/gh-workflows/.github/actions/docker-build@v6
        with:
          registry: registry.cern.ch
          stage: refextract
          image: cern-sis/inspirehep/refextract
          cache: false
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Deploy QA
        uses: cern-sis/gh-workflows/.github/actions/kubernetes-project-new-images@v6.4
        with:
          event-type: update
          repo: cern-sis/kubernetes-inspire
          images: registry.cern.ch/cern-sis/inspirehep/refextract@${{ steps.build.outputs.image-digest }}
          token: ${{ secrets.PAT_FIRE_EVENTS_ON_CERN_SIS_KUBERNETES }}
