name: Pull request master

on:
  push:
    branches: [master]

jobs:
  tests:
    uses: ./.github/workflows/test.yml
  bump_version:
      needs: [tests]
      uses: ./.github/workflows/bump-and-publish.yml
      secrets: inherit
