name: Release

on:
  release:
    types: [released]

defaults:
  run:
    shell: bash

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git push --force --follow-tags origin ${{ github.ref_name }}:prod

      - name: Generate metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            registry.cern.ch/cern-sis/inspirehep/refextract
          tags: "type=sha"

      - name: send event inspire
        uses: cern-sis/gh-workflows/.github/actions/kubernetes-project-new-images@v6.4
        with:
          repo: cern-sis/kubernetes-inspire
          event-type: release
          images: ${{ env.DOCKER_METADATA_OUTPUT_TAGS }}
          token: ${{ secrets.PAT_FIRE_EVENTS_ON_CERN_SIS_KUBERNETES }}
